### ISSUE TITLE
Image dosen't boot on RPI4

### ISSUE THREAD

**Issue by DorfNKB** [Telraam/Telraam-RPi#14]
The image from 
https://telraam-api.net/telraam-sd-image.zip 
dosen't boot on a rasperry pi 4.

**Comment by Telraam** [comment]
Dear DorfNKB,

Thank you for the feedback. This is (unfortunately) expected at the current stage of the development, as right now we only support (a.k.a. compile an image for) the 3A+ model (and unofficially the 3B+ since it is the same hardware just slightly different ports).  Later on we might provide images for the newer RPI models (depending on our resources and how long the 3A+ model stays on the market), but we are also considering moving to custom hardware (but only if we can keep the price point at the current level). Right now we are unable to give a timeline for this, but we will keep your feedback for future development for sure.

Best regards,
The Telraam Team

**Comment by Wildspoor-NL** [comment]
I'm having the same problem. 
Unfortunately, finally it would be a good idea for my community to be informed about the traffic flow.
Regards,
Rob
=====

**Comment by ShamalHPW** [comment]
@telraam Any update on RPI4 support?

**Comment by Telraam** [comment]
We are very busy with work on the back and front end, the improvements there are - unfortunately - higher priority for the moment. But the RPI4 image is still on our to do list (and we have already bought a few units for testing).

**Comment by ghost** [comment]
Hi! Just wanted to add my voice to those who'd love to join the Telraam network using a home-built RPI4 system. I have the hardware ready to go -- just need the software to support it. Many thanks for all your work on this.

**Comment by cheeseonpost** [comment]
Its now just two weeks short of a year down the line from the last comment. Can anyone provide an update on a workaround for this for the Pi4 please? We are so keen to trial this and use with other open data sources.

**Comment by Telraam** [comment]
Hi all,

Because we are working on a microcontroller based version 2 of the telraam camera sensor, we will not be creating an image for the RPi4.

Best regards,
The Telraam Team
