### ISSUE TITLE
Incorrectly counted traffic in one way street?

### ISSUE THREAD

**Issue by verheyenkoen** [Telraam/Telraam-RPi#2]
[This telraam report](https://www.telraam.net/nl/location/522820/2019-03-01/2019-06-07) in my street (so I'm not the owner but I know where it is) is reporting car & lorry traffic in both directions while it is a one way street which (in my opinion) is honoured almost perfectly. `L > R` car traffic is a lot higher than `R > L` traffic (while I think it maybe needs to be the other way around; the house is on the left side of the street in the driving direction, so most traffic is coming from the right of the telraam). For lorries the `L > R` and `R > L` figures are in the same range which is especially strange for a one way street.

**Comment by smaerivo** [comment]
Thank you for the information; I've relayed it internally so we can take a look at it.

**Comment by papics** [comment]
Dear Koen, thank you for the feedback, here is a short explanation of why you see these:
- the L>R and R>L directions are indeed reverse, this is a leftover effect from the early development phase, when the first development units had cameras hang 180 degrees rotated in comparison to how the 'commercial' installation setup is. We will update the database and the UI to reflect these changes in the near future.
- Concerning the ~10% of the car traffic that seems to be going against the legal one way direction, these are misclassified cyclists for sure. Right now the classifier algorithm is not tuned for each camera (and each direction per camera), as it is calibrated on an initial test data set coming from a few selected test cameras. We are using distance independent variables in the classification (meaning that the distance between the road surface and the camera does not influence the process, so it can be generalised), but there is still a small dependence on the view angle from the camera to the street, so it is expected that this initial general classifier setup will not be 100% correct. In the future as sufficient data is gathered for each camera, we plan to build camera- and traffic direction specific classifiers, this will remove the inaccuracy introduced by using a generalised classifier. Beyond this, there is the issue that cyclists sometimes ride in close pairs along each other, or in small groups, and it is likely that in these instances the separation between individual cyclists is not large enough to be identified independently, meaning that the pair, or small group of multiple cyclists will be observed as one larger object. This larger object will be classified by the classifier as a car, or if the group is large enough, even a truck... This explains why there are cars seemingly illegally driving in the wrong direction.
- For lorries, the figures are actually similar to cars, looking at the data at https://www.telraam.net/nl/location/522820/2019-03-01/2019-06-07 (where the figure showing the L/R directions is actually updated to a better visual representation since yesterday), the average number of lorries per day in the right direction is 142, while in the opposite direction it is 25. With lorries, the ones seemingly riding in the wrong direction are again likely unresolved group of cyclists.

**Comment by verheyenkoen** [comment]
Thanks for the answer. I hope you can get all this fine-tuned in the future.

Btw, these are probably also a lot of cargo bikes as there is a kindergarten/preschool 30m from there and a cargo bike transport company (Cargo Velo) at 200m and obviously a lot of young families in the area for which cargo bikes are a sublime way of transportation. Maybe it is an idea have one way streets configured in the device (or processing software) and for those locations "downgrade" the car and lorry traffic going against the one way direction to bike traffic in the stats. Cars (and definitely lorries) going in the wrong direction in that place are very rare to non-existent (unless maybe when there is road construction ongoing, which happened last year for a couple of days, before Telraam launched). I guess the odd one out car actually driving in the wrong way is less important to count than  the amount of false positives that are in the stats now.

Anyway, you are doing a great job!

**Comment by papics** [comment]
Thanks for the suggestions about the downgrading in one way streets, this is definitely a possible shortcut option before we come up with a more false-positive-proof classifier! We will keep this in mind. (Cargo bikes are in most cases handled well by our classifier. Except if one parent is riding a cargo bike and another one just next to it a normal one, that would of course cause a problem...)
